### ISSUE TITLE
Empty responses = error

### ISSUE THREAD

**Issue by ArnaudLier** [RedstoneGamez/Pterodactyl.js#1]
Hello, sending a power action or a command return a empty response by default, is it possible to desactivate this error?

**Comment by ArnaudLier** [comment]
(The error occurs when trying to get JSON from nothing)

**Comment by RedstoneGamez** [comment]
Hello, I have fixed this issue by updating the call function with the no-body rule for future cases that are similar and have published it to npm as v2.1.1.
