### ISSUE TITLE
This is not an issue, but are there any docs?

### ISSUE THREAD

**Issue by ghost** [RedstoneGamez/Pterodactyl.js#2]
There are no docs at all, how am I supposed to use this?

**Comment by RedstoneGamez** [comment]
Hello @johnmsweet,

There is not currently any documentation that is available. There should be available documentation in the coming months but if you require any assistance, have any questions as to how to do anything, or would like more about the wrapper, you can join our discord at https://discord.gg/xUR2ydt

Thank you!

**Comment by ghost** [comment]
Thanks!
